### ISSUE TITLE
Template naming conventions

### ISSUE THREAD

**Issue by anweiss** [azurermtemplates/azurermtemplates#114]
Would probably be best if we came up with some template naming conventions to include in the contributor guidelines. We may even want to re-organize the directory structure of this repository as the number of templates continues to grow.

**Comment by singhkays** [comment]
@anweiss it might be hard to drive a consistent naming across all the different scenarios template might accomplish. But we're open to suggestions.

**Comment by anweiss** [comment]
Good point @singhkay. At least, if we can find a way to group them that might be helpful.

**Comment by singhkays** [comment]
@anweiss for the vms we've tried to do something like below to group them by OS 
![image 6](https://cloud.githubusercontent.com/assets/6164178/6953619/5f30d886-d87f-11e4-967e-ed0b14ea4f87.png)

**Comment by anweiss** [comment]
Ok awesome...will stick with this structure for PRs
