### ISSUE TITLE
activedirectorynewdomain template references missing files

### ISSUE THREAD

**Issue by jahabrewer** [azurermtemplates/azurermtemplates#274]
I've been excitedly consuming the activedirectorynewdomain (https://github.com/azurermtemplates/azurermtemplates/tree/master/activedirectorynewdomain) template for a couple of days. Minor issue, it seems this version, which is non-HA, needs a couple of files (vnet.json, vnet-with-dns-server.json) that aren't present. They **are** present in the HA version (https://github.com/azurermtemplates/azurermtemplates/tree/master/activedirectorynewdomain-ha-2-dc). I've been able to work around this by giving the HA version's URL for the parameter AssetLocation.

@simongdavies

**Comment by singhkays** [comment]
@simongdavies can you take a look at this?
