### ISSUE TITLE
Ubuntu Chef template issue with public IP DNS name

### ISSUE THREAD

**Issue by dtzar** [azurermtemplates/azurermtemplates#95]
https://github.com/azurermtemplates/azurermtemplates/tree/master/ubuntu-vm-with-chef
Has a problem because the "dnsName" : "[variables('subnet1Name')]" needs to be globally unique.  It should have a variable for user to input on the template or scrap the public dns name.
When you run the template, it gives you the error
"DNS record subnet-1.westus.cloudapp.azure.com. is already used by another public IP. "

**Comment by singhkays** [comment]
Thanks for the catch @dtzar 

@KundanaP can you fix the above template?

**Comment by singhkays** [comment]
Kundana fixed this, closing
